### PR TITLE
Add Storybook to GitHub Pages

### PR DESCRIPTION
**Pull request by 0ortmann**
I verified that the story book get's pushed to the `gh-pages` branch [with this action](https://github.com/tenzir/ui-component-library/pull/38/checks?check_run_id=830656038).

As of now, the deployment is restricted to `master` merges, hence the latest action runs of this action won't reflect that step.

### CODE REVIEW

**Comment by 0ortmann** [comment]
Since both @rolandpeelen and @0ortmann worked on this, I think it makes most sense if either of you review this @dominiklohmann @mavam .

**Comment by 0ortmann** [comment]
I now rebased this on `master` and restored the lost files. We're good to merge :)

**Comment by mavam** [comment]
Wait, can we put the storybook to the top-level bar of links?

**Comment by 0ortmann** [comment]
Added it in there.

**Pull request merged**
